#!/usr/bin/env node

import { Command } from 'commander';
import fs from 'fs/promises';
import path from 'path';
import {
  loadConfig,
  getCacheDir,
  getLibraryPath,
  loadMetadata,
  getPluginDir,
  ensureDir,
  log,
  formatRelativeTime
} from './utils.js';

const program = new Command();

/**
 * Generate skill content from cached documentation
 */
async function generateSkillContent(library, metadata, template = 'expert') {
  const skillName = `${library}-${metadata.version.split('.')[0]}-expert`;
  const docsPath = `.claude/docs/${library}/${metadata.version}`;

  const content = `---
name: ${skillName}
description: Expert knowledge of ${library} ${metadata.version} based on official documentation
version: ${metadata.version}
library: ${library}
docs_path: ${docsPath}
last_updated: ${new Date().toISOString().split('T')[0]}
auto_activate: true
activation_patterns:
  - "package.json contains ${library}"
  - "user asks about ${library}"
---

# ${library.charAt(0).toUpperCase() + library.slice(1)} ${metadata.version} Expert

I have comprehensive knowledge of ${library} version ${metadata.version} based on the complete official documentation cached locally.

## Documentation Source

- **Source**: ${metadata.source_url}
- **Version**: ${metadata.version}
- **Cached**: ${formatRelativeTime(metadata.fetched_at)}
- **Pages**: ${metadata.page_count}
- **Source Type**: ${metadata.source_type}

## What I Know

I can help you with ${library} by referencing the cached documentation at:
\`${docsPath}\`

This documentation was fetched from the official source and contains accurate, version-specific information.

## Usage

I automatically activate when you're working on ${library} projects. Ask me questions like:

- "How do I use [feature] in ${library}?"
- "What's the best way to [task]?"
- "Show me an example of [pattern]"
- "Help me debug this ${library} issue"

## Version-Specific Guidance

This skill references ${library} version ${metadata.version} specifically. I will provide guidance based on this exact version.

---

*Generated by doc-fetcher plugin*
*Documentation version: ${metadata.version}*
*Last updated: ${new Date().toISOString().split('T')[0]}*
`;

  return {
    skillName,
    content
  };
}

/**
 * Save skill to file
 */
async function saveSkill(skillName, content) {
  const pluginDir = getPluginDir();
  const skillsDir = path.join(pluginDir, 'skills');
  const skillDir = path.join(skillsDir, skillName);

  await ensureDir(skillDir);

  const skillPath = path.join(skillDir, 'SKILL.md');
  await fs.writeFile(skillPath, content, 'utf-8');

  // Create metadata file
  const metadataPath = path.join(skillDir, '.doc-reference.json');
  const metadata = {
    generated_at: new Date().toISOString(),
    auto_generated: true,
    template_used: 'expert'
  };
  await fs.writeFile(metadataPath, JSON.stringify(metadata, null, 2), 'utf-8');

  return skillPath;
}

/**
 * Generate skill from cached documentation
 */
async function generateSkill(library, version, options) {
  log(`\\nGenerating skill for ${library}${version ? ` v${version}` : ''}...\\n`, 'info');

  // Load config
  const config = await loadConfig();
  const cacheDir = config.cache_directory || getCacheDir();

  // Load metadata
  const libraryPath = getLibraryPath(cacheDir, library, version || 'latest');
  const metadata = await loadMetadata(libraryPath);

  if (!metadata) {
    throw new Error(`No cached documentation found for ${library}. Run /fetch-docs ${library} first.`);
  }

  // Generate skill content
  log('[1/2] Generating skill content...', 'info');
  const { skillName, content } = await generateSkillContent(library, metadata, options.template);

  // Save skill
  log('[2/2] Saving skill...', 'info');
  const skillPath = await saveSkill(skillName, content);

  // Update metadata to mark skill as generated
  metadata.skill_generated = true;
  metadata.skill_path = `skills/${skillName}`;

  const metadataPath = path.join(libraryPath, 'index.json');
  await fs.writeFile(metadataPath, JSON.stringify(metadata, null, 2), 'utf-8');

  log(`\\n✓ Skill generated successfully!\\n`, 'info');
  log(`  Name: ${skillName}`, 'info');
  log(`  Location: ${skillPath}`, 'info');
  log(`  Auto-activation: enabled\\n`, 'info');

  log(`The skill is now active. Ask me anything about ${library} ${metadata.version}!\\n`, 'info');

  return {
    skillName,
    skillPath,
    library,
    version: metadata.version
  };
}

/**
 * CLI setup
 */
program
  .name('generate-skill')
  .description('Generate a Claude Code skill from cached documentation')
  .argument('<library>', 'Library name (e.g., nextjs, react)')
  .argument('[version]', 'Specific version (defaults to latest)')
  .option('-t, --template <template>', 'Skill template to use', 'expert')
  .option('-o, --output <path>', 'Custom output path')
  .action(async (library, version, options) => {
    try {
      await generateSkill(library, version, options);
      process.exit(0);
    } catch (error) {
      log(`\\n✗ Error: ${error.message}\\n`, 'error');
      process.exit(1);
    }
  });

program.parse();

export default generateSkill;
